# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-21 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20180921_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='u_icon',
            field=models.ImageField(upload_to='%Y/%m/%d/icons'),
        ),
    ]
